const sections = [
  {key:'HC', name:'Human Capital', th:'ทุนมนุษย์', note:'ความรู้ ประสบการณ์ และทักษะทางเทคนิคของทีม', items:[
    ['HC1','สมาชิกในทีมมีความรู้และทักษะทางเทคนิคที่เพียงพอต่อการปฏิบัติงานโครงการ','Members of your project team possess the technical knowledge required by the work of the project.'],
    ['HC2','สมาชิกในทีมมีประสบการณ์ในการทำงานโครงการลักษณะใกล้เคียงกันมาก่อน','Members of your project team have substantial prior experience with projects of this type.'],
    ['HC3','ทีมโครงการของท่านมีความเชี่ยวชาญเฉพาะทางที่เพียงพอสำหรับแก้ไขปัญหาทางเทคนิคที่พบเจอ','Your project team collectively holds the specialized expertise needed to solve the technical problems it encounters.']]},
  {key:'EI',name:'Emotional Intelligence',th:'ความฉลาดทางอารมณ์',note:'การรับรู้ ควบคุม และใช้ความเข้าใจด้านอารมณ์',items:[
    ['EI1','สมาชิกในทีมสามารถรับรู้และเข้าใจอารมณ์ของตัวเองในสถานการณ์ต่างๆ ได้ดี (SEA)','Members of your project team can clearly perceive and understand their own emotions in different situations. (SEA)'],['EI2','สมาชิกในทีมสามารถควบคุมอารมณ์ของตัวเองได้ดีแม้อยู่ภายใต้แรงกดดัน (ROE)','Members of your project team can regulate their own emotions well even under pressure. (ROE)'],['EI3','สมาชิกในทีมสามารถเข้าใจและเห็นอกเห็นใจความรู้สึกของเพื่อนร่วมทีมทุกคน (OEA)','Members of your project team can understand and empathize with the feelings of every teammate. (OEA)'],['EI4','สมาชิกในทีมสามารถใช้ความเข้าใจด้านอารมณ์ของตัวเองเพื่อกระตุ้นแรงจูงใจ (UOE)','Members of your project team can use their own emotional understanding to motivate themselves. (UOE)']]},
  {key:'TA',name:'Team Autonomy',th:'ความเป็นอิสระของทีม',note:'อำนาจของทีมในการวางแผน ตัดสินใจ และกำหนดวิธีทำงาน',items:[['TA1','ทีมมีอำนาจควบคุมต่อวิธีการทำงานเพื่อบรรลุเป้าหมายที่ได้รับมอบหมาย','Your project team decides for itself how to carry out its work.'],['TA2','ทีมโครงการมีอำนาจในการวางแผนและจัดลำดับความสำคัญของงานของตนเองภายในสปรินต์หรือรอบการทำงาน','Your project team has the authority to plan and prioritize its own tasks within a sprint or iteration.'],['TA3','ทีมโครงการสามารถตัดสินใจในประเด็นทางเทคนิคได้เองโดยไม่ต้องขออนุมัติจากภายนอกทีม','Your project team can make technical decisions without seeking approval from outside the team.'],['TA4','ทีมโครงการสามารถกำหนดแนวทางรับมือได้เองเมื่อเงื่อนไขของโครงการเปลี่ยนแปลงไป','Your project team is able to determine how to respond when project conditions change.']]},
  {key:'CI',name:'Customer Involvement',th:'การมีส่วนร่วมของลูกค้า',note:'การมีส่วนร่วม ข้อมูลป้อนกลับ และความรู้จากลูกค้าหรือฝ่ายธุรกิจ',items:[['CI1','ลูกค้าหรือตัวแทนฝ่ายธุรกิจเข้ามามีส่วนร่วมอย่างแข็งขันในการทำงานของทีมโครงการ','Customer or business representatives take an active part in the work of your project team.'],['CI2','ลูกค้าหรือตัวแทนฝ่ายธุรกิจพร้อมให้ข้อมูลเมื่อทีมต้องการความชัดเจนเกี่ยวกับความต้องการ','Customer or business representatives are available when the team needs clarification of requirements.'],['CI3','ทีมได้รับข้อมูลป้อนกลับจากลูกค้าอย่างสม่ำเสมอตลอดโครงการ มิใช่เฉพาะช่วงส่งมอบ','Customer feedback is obtained regularly throughout the project rather than only at delivery.'],['CI4','ลูกค้าหรือตัวแทนฝ่ายธุรกิจให้ความรู้ที่ช่วยให้ทีมเข้าใจปัญหาได้ดียิ่งขึ้น','Customer or business representatives contribute knowledge that improves the team’s understanding of the problem.']]},
  {key:'PS',name:'Team Psychological Safety',th:'ความปลอดภัยทางจิตใจของทีม',note:'สภาพแวดล้อมที่สมาชิกกล้าพูดคุย ขอความช่วยเหลือ และแสดงความคิดเห็น',items:[['PS1','หากสมาชิกในทีมทำผิดพลาด มักจะไม่ถูกนำมาใช้ตำหนิซ้ำภายหลัง','If members of your project team make a mistake, it is usually not held against them later.'],['PS2','สมาชิกในทีมกล้าหยิบยกปัญหาหรือประเด็นที่ยากลำบากขึ้นมาพูดคุยได้','Members of your project team are able to raise problems and difficult issues.'],['PS3','สมาชิกในทีมไม่ปฏิเสธหรือกีดกันเพื่อนร่วมทีมที่มีความคิดเห็นแตกต่าง','Members of your project team do not reject or exclude a teammate for having a different opinion.'],['PS4','การขอความช่วยเหลือจากสมาชิกคนอื่นในทีมสามารถทำได้โดยง่าย','It is easy to ask other members of your project team for help.'],['PS5','ทักษะและความสามารถของสมาชิกแต่ละคนได้รับความเห็นคุณค่าและถูกนำไปใช้ประโยชน์โดยทีม','The skills and talents of each member are valued and utilized by your project team.']]},
  {key:'TC',name:'Team Competency',th:'สมรรถนะของทีม',note:'การประสานงาน บูรณาการความรู้ เรียนรู้ และปรับวิธีทำงาน',items:[['TC1','ทีมโครงการของท่านประสานงานระหว่างสมาชิกและบทบาทต่างๆ ได้อย่างมีประสิทธิผล','Your project team coordinates its work effectively across members and roles.'],['TC2','ทีมโครงการของท่านบูรณาการความรู้ที่แตกต่างกันของสมาชิกเข้าด้วยกันในการแก้ปัญหา','Your project team integrates the different knowledge of its members when solving problems.'],['TC3','ทีมโครงการของท่านเรียนรู้จากประสบการณ์ของตนเองและปรับปรุงวิธีการทำงานให้ดีขึ้นอย่างต่อเนื่อง','Your project team learns from its own experience and improves the way it works over time.'],['TC4','ทีมโครงการของท่านสื่อสารเกี่ยวกับสถานะของงานระหว่างกันได้อย่างมีประสิทธิผล','Your project team communicates effectively about the state of the work.'],['TC5','ทีมโครงการของท่านสามารถปรับเปลี่ยนวิธีการทำงานของตนเองได้เมื่อความต้องการของโครงการเปลี่ยนแปลงไป','Your project team is able to reconfigure the way it works when the demands of the project change.']]},
  {key:'IP',name:'IT Project Success',th:'ความสำเร็จของโครงการไอที',note:'ขอบเขต คุณภาพ เวลา งบประมาณ ความพึงพอใจ และการใช้งานจริง',items:[['IP1','โครงการที่ทีมของท่านส่งมอบเป็นไปตามขอบเขตและคุณภาพงานที่ตกลงกันไว้','The projects delivered by your team meet their agreed scope and quality requirements.'],['IP3','ผู้มีส่วนได้ส่วนเสียของโครงการที่ทีมของท่านส่งมอบมีความพึงพอใจต่อผลลัพธ์','The stakeholders of the projects delivered by your team are satisfied with the outcome.'],['IP4','ระบบที่ทีมของท่านส่งมอบถูกนำไปใช้งานจริงตามที่ผู้ใช้งานตั้งใจไว้','The systems delivered by your team are actually used as intended by their users.']]},
  {key:'DV',name:'Digital Business Value',th:'คุณค่าทางธุรกิจดิจิทัล',note:'ผลลัพธ์ของโครงการต่อการดำเนินงาน การบริหาร กลยุทธ์ และองค์กร',items:[['DV1','โครงการที่ทีมของท่านส่งมอบช่วยเพิ่มประสิทธิภาพการดำเนินงานขององค์กร (ด้านปฏิบัติการ)','The projects delivered by your team improve the operational efficiency of the organization.'],['DV2','โครงการที่ทีมของท่านส่งมอบช่วยยกระดับการตัดสินใจและการควบคุมเชิงบริหารขององค์กร (ด้านการบริหารจัดการ)','The projects delivered by your team improve managerial decision making and control.'],['DV3','โครงการที่ทีมของท่านส่งมอบช่วยเสริมความแข็งแกร่งให้แก่ตำแหน่งเชิงกลยุทธ์ขององค์กร (ด้านกลยุทธ์)','The projects delivered by your team strengthen the strategic position of the organization.'],['DV4','โครงการที่ทีมของท่านส่งมอบช่วยเสริมสร้างโครงสร้างพื้นฐานไอทีที่พร้อมรองรับการริเริ่มใหม่ในอนาคต (ด้านโครงสร้างพื้นฐานไอที)','The projects delivered by your team strengthen the IT infrastructure available for future initiatives.'],['DV5','โครงการที่ทีมของท่านส่งมอบสนับสนุนการเปลี่ยนแปลงองค์กรในวงกว้างและวิธีการทำงานรูปแบบใหม่ (ด้านองค์กร)','The projects delivered by your team support wider organizational change and new ways of working.']]}
];
const scale=[['1','ไม่เห็นด้วยอย่างยิ่ง','Strongly disagree'],['2','ไม่เห็นด้วย','Disagree'],['3','ไม่แน่ใจ','Neither agree nor disagree'],['4','เห็นด้วย','Agree'],['5','เห็นด้วยอย่างยิ่ง','Strongly agree']];
let sectionIndex=0;let answers={};let language='th';
const $=id=>document.getElementById(id);const allItems=()=>sections.flatMap(s=>s.items);
function render(){const s=sections[sectionIndex];$('section-kicker').textContent='ส่วนที่ '+(sectionIndex+1)+' จาก '+sections.length;$('section-title').textContent=s.name;$('section-description').textContent=s.th;$('section-number').textContent=String(sectionIndex+1).padStart(2,'0');$('aside-title').textContent=s.name;$('aside-note').textContent=s.note;$('prev-btn').disabled=sectionIndex===0;$('prev-btn').style.opacity=sectionIndex===0?.45:1;$('next-btn').innerHTML=sectionIndex===sections.length-1?'ส่งคำตอบ <span>✓</span>':'ถัดไป <span>→</span>';$('survey-form').innerHTML=s.items.map(([id,th,en])=>'<fieldset class="question"><div class="question-label"><span class="q-code">'+id+'</span><p class="question-title">'+(language==='th'?th:en)+'<small>'+(language==='th'?en:th)+'</small></p></div><div class="options">'+scale.map(([v,thLabel,enLabel])=>'<div class="option"><input type="radio" id="'+id+'-'+v+'" name="'+id+'" value="'+v+'" '+(answers[id]===v?'checked':'')+'/><label for="'+id+'-'+v+'"><b>'+v+'</b>'+(language==='th'?thLabel:enLabel)+'</label></div>').join('')+'</div></fieldset>').join('');$('survey-form').querySelectorAll('input').forEach(input=>input.addEventListener('change',e=>{answers[e.target.name]=e.target.value;updateProgress()}));updateProgress();window.scrollTo({top:0,behavior:'smooth'})}
function updateProgress(){const answered=allItems().filter(([id])=>answers[id]).length;const pct=Math.round(answered/allItems().length*100);$('progress-percent').textContent=pct+'%';$('progress-bar').style.width=pct+'%'}
function start(){$('welcome').classList.add('hidden');$('complete').classList.add('hidden');$('survey').classList.remove('hidden');render()}
async function submitToGoogleSheets(){const payload={timestamp:new Date().toISOString(),language,answers:Object.fromEntries(allItems().map(([id])=>[id,Number(answers[id])]))};if(!window.GOOGLE_SCRIPT_URL)return false;await fetch(window.GOOGLE_SCRIPT_URL,{method:'POST',mode:'no-cors',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(payload)});return true}
async function finish(){$('next-btn').disabled=true;$('next-btn').textContent='กำลังบันทึก…';const sent=await submitToGoogleSheets().catch(()=>false);$('survey').classList.add('hidden');$('complete').classList.remove('hidden');$('answered-count').textContent=Object.keys(answers).length+' / '+allItems().length;$('submit-status').textContent=sent?'บันทึกใน Google Sheets แล้ว':'ยังไม่ได้ตั้งค่า Google Sheets';if(!sent)$('submit-status').style.color='#b7791f';window.scrollTo({top:0,behavior:'smooth'})}
$('start-btn').addEventListener('click',start);$('prev-btn').addEventListener('click',()=>{if(sectionIndex>0){sectionIndex--;render()}});$('next-btn').addEventListener('click',()=>{const missing=sections[sectionIndex].items.filter(([id])=>!answers[id]);if(missing.length){alert('กรุณาตอบคำถามให้ครบอีก '+missing.length+' ข้อก่อนดำเนินการต่อ');return}if(sectionIndex<sections.length-1){sectionIndex++;render()}else finish()});$('restart-btn').addEventListener('click',()=>{answers={};sectionIndex=0;start()});document.querySelectorAll('.lang').forEach(btn=>btn.addEventListener('click',()=>{language=btn.dataset.language;document.querySelectorAll('.lang').forEach(x=>x.classList.toggle('active',x===btn));if(!$('survey').classList.contains('hidden'))render()}));
