document.addEventListener('DOMContentLoaded',()=>{const w=document.querySelector('#welcome');if(!w)return;const d={th:{h:'คำชี้แจง',items:[
'แบบสอบถามฉบับนี้เป็นส่วนหนึ่งของการศึกษาระดับปริญญาเอก สาขาการจัดการเทคโนโลยีสารสนเทศ มีวัตถุประสงค์เพื่อศึกษาว่าทรัพยากรเชิงกลยุทธ์ (ทุนมนุษย์และความฉลาดทางอารมณ์) และปัจจัยความสำเร็จเชิงวิกฤตแบบอไจล์ (ความเป็นอิสระของทีมและการมีส่วนร่วมของลูกค้า) ถูกแปลงผ่านสมรรถนะของทีมไปสู่ความสำเร็จของโครงการไอทีและคุณค่าทางธุรกิจดิจิทัลอย่างไร โดยมีความปลอดภัยทางจิตวิทยาของทีมทำหน้าที่เป็นทั้งตัวแปรส่งผ่านและตัวแปรกำกับ',
'ผู้ตอบแบบสอบถามที่เข้าเกณฑ์ ได้แก่ สมาชิกหลักหรือผู้นำทีมของทีมโครงการไอทีที่ใช้แนวทาง Agile หรือ Hybrid Agile เช่น Developer/Engineer, Scrum Master, Product Owner, Project Manager, Agile Coach, Business Analyst หรือที่ปรึกษา และต้องมีประสบการณ์ตรงตั้งแต่ 3 ปีขึ้นไป ทั้งผู้ตอบสัญชาติไทยและชาวต่างชาติสามารถเข้าร่วมได้',
'แบบสอบถามแบ่งเป็น 4 ตอน ได้แก่ คำถามคัดกรองคุณสมบัติ ข้อมูลทั่วไปและบริบทโครงการ ตัวแปรต้น และตัวแปรผลลัพธ์ รวมข้อคำถามหลัก 35 ข้อ พร้อมข้อตรวจสอบความตั้งใจ 2 ข้อ และคำถามปลายเปิดสำหรับข้อเสนอแนะเพิ่มเติม',
'กรุณาตอบแบบสอบถามตามความเป็นจริงและครบทุกข้อ ใช้เวลาประมาณ 10–15 นาที ไม่มีคำตอบที่ถูกหรือผิด ผู้วิจัยสนใจความคิดเห็นของท่านตามสภาพความเป็นจริงเท่านั้น',
'ข้อมูลจะถูกเก็บเป็นความลับ ใช้เพื่อการศึกษาวิจัย และนำเสนอผลในภาพรวมเชิงสถิติ ท่านสามารถยุติการตอบแบบสอบถามได้ทุกเมื่อโดยไม่มีผลกระทบใด ๆ',
'การตอบแบบสอบถามและส่งกลับ ถือเป็นการให้ความยินยอมเข้าร่วมการวิจัยโดยสมัครใจ',
'แบบสอบถามจัดทำเป็นภาษาไทยและภาษาอังกฤษ เพื่อให้ผู้ตอบเลือกภาษาที่ถนัดได้ ผู้วิจัยขอขอบพระคุณท่านเป็นอย่างสูงที่กรุณาสละเวลาตอบแบบสอบถาม'],note:'หมายเหตุเกี่ยวกับอีเมล: ระบบจะเก็บอีเมลที่ท่านกรอกไว้ใน Google Sheets เพื่อระบุรายการคำตอบและใช้ในการวิจัยเท่านั้น โดยจะไม่เผยแพร่ต่อสาธารณะ'},en:{h:'Instructions',items:[
'This questionnaire is part of a doctoral study in Information Technology Management. It examines how strategic resources (human capital and emotional intelligence) and Agile critical success factors (team autonomy and customer involvement) are converted through team competency into IT project success and digital business value, with team psychological safety serving as both a mediating and a moderating variable.',
'Eligible respondents are core team members or team leaders of IT project teams using an Agile or Hybrid Agile approach, such as Developer/Engineer, Scrum Master, Product Owner, Project Manager, Agile Coach, Business Analyst, or Consultant, with at least three years of direct experience. Thai and foreign respondents are welcome.',
'The questionnaire has four parts: respondent screening, general respondent and project-context information, independent variables, and outcome variables. It contains 35 core items, two attention-check items, and an open-ended question for further suggestions.',
'Please answer every item truthfully and completely. The questionnaire takes approximately 10–15 minutes. There are no right or wrong answers; the researcher is interested only in your honest opinion based on actual circumstances.',
'The information will be kept confidential, used for research purposes, and reported only in aggregate statistical form. You may withdraw from the survey at any time without any consequence.',
'Completing and submitting this questionnaire constitutes voluntary consent to participate in the research.',
'The questionnaire is available in Thai and English so that respondents can choose their preferred language. The researcher sincerely thanks you for taking the time to complete it.'],note:'Email notice: The email address you provide will be stored in Google Sheets only to identify the response record and support the research. It will not be published publicly.'}};const p=document.createElement('section');p.id='research-instructions';p.className='instructions-panel';p.innerHTML=Object.entries(d).map(([k,v])=>'<div class="instructions-content '+(k==='en'?'hidden':'')+'" data-language-content="'+k+'"><div class="instruction-heading">'+v.h+'</div><ol>'+v.items.map(x=>'<li>'+x+'</li>').join('')+'</ol><div class="instruction-note">'+v.note+'</div></div>').join('');const n=w.querySelector('.notice');w.insertBefore(p,n||w.querySelector('#start-btn'));document.querySelectorAll('.lang').forEach(b=>b.addEventListener('click',()=>p.querySelectorAll('[data-language-content]').forEach(x=>x.classList.toggle('hidden',x.dataset.languageContent!==b.dataset.language))));});
